<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="0">

  <testsuite name="e2e.nw"
    errors="1" failures="0" hostname="" id="" package="e2e.nw" skipped="1"
    tests="0" time="0.000" timestamp="">
  

  
    <system-err>
        WebDriverError: An error occurred while creating a new GeckoDriver session: [WebDriverError] Process unexpectedly closed with status 1
  Verify if GeckoDriver is configured correctly; using:
  {
     start_process: true,
     server_path: &#39;/home/ctux/Projects/vitejs-react-ts-template/node_modules/.pnpm/geckodriver@3.0.2/node_modules/geckodriver/geckodriver&#39;,
     port: 4444,
     host: &#39;localhost&#39;,
     ssl: false,
     default_path_prefix: &#39;&#39;,
     proxy: undefined,
     cli_args: []
  }

 
  More info might be available in the log file: /home/ctux/Projects/vitejs-react-ts-template/logs/e2e.nw_geckodriver.log
    </system-err>
  

    
    <error message="An error occurred while creating a new GeckoDriver session: [WebDriverError] Process unexpectedly closed with status 1"><![CDATA[
      WebDriverError: An error occurred while creating a new GeckoDriver session: [WebDriverError] Process unexpectedly closed with status 1
    at Object.throwDecodedError (/home/ctux/Projects/vitejs-react-ts-template/node_modules/.pnpm/selenium-webdriver@4.1.1/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/home/ctux/Projects/vitejs-react-ts-template/node_modules/.pnpm/selenium-webdriver@4.1.1/node_modules/selenium-webdriver/lib/http.js:548:13)
    at Executor.execute (/home/ctux/Projects/vitejs-react-ts-template/node_modules/.pnpm/selenium-webdriver@4.1.1/node_modules/selenium-webdriver/lib/http.js:474:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
      ]]></error>  

  
    
    <testcase
      name="should increment counter" classname="e2e.nw">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
